name: Build and Push Docker Image to GCR

on:
  push:
    branches:
      - main  # This triggers the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Google Cloud CLI
      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0.5.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Authenticate with Google Cloud
      - name: Authenticate to GCP
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > ${HOME}/gcloud-service-key.json
          gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
          gcloud auth configure-docker --quiet

      # Debug: Print project ID to check if it's being set correctly
      - name: Debug project ID
        run: echo "Project ID is: ${{ secrets.GCP_PROJECT_ID }}"

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/hello-world:${{ github.sha }} .

      # Push the Docker image to GCR
      - name: Push Docker image to GCR
        run: |
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/hello-world:${{ github.sha }}
