#.
name: Build and Push Docker Image to GCR

on:
  push:
    branches:
      - main  # This triggers the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Google Cloud CLI
      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0.5.0
        with:
          project_id: ${{ secrets.GCP_PROJECT }}  # Use GCP_PROJECT instead of GCP_PROJECT_ID
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Authenticate with Google Cloud
      - name: Authenticate to GCR
        run: |
          gcloud auth configure-docker --quiet

      # Debug: Print project ID to check if it's being set correctly
      - name: Debug GCP_PROJECT Secret
        run: echo "GCP_PROJECT is ${{ secrets.GCP_PROJECT }}"

    
      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/my-repo/hello-world:${{ github.sha }} .

      # Push the Docker image to GCR
      - name: Push Docker image to GCR
        run: |
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/my-repo/hello-world:${{ github.sha }}
